---

- name: Revoke SSH access
  authorized_key:
    user: "{{ user_name }}"
    state: absent
    key: "{{ lookup('file', '../../../sshkeys/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - revoke
